[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#FF6900"
backgroundColor = "#fdf7f4"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
